schema_version: 1

context:
  version: "0.8.0"

package:
  name: rustling
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/rustling/rustling-${{ version }}.tar.gz
  sha256: 04d769e50ff2c8b0bc5fb178f0a1dba578427b6a7d9027253366d1ac8922e1fd

build:
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - ${{ stdlib('c') }}
  host:
    - python
    - pip
    - maturin >=1.0,<2
  run:
    - python

tests:
  - python:
      imports:
        - rustling

about:
  homepage: https://github.com/jacksonllee/rustling
  license: MIT
  license_file:
    - LICENSE.md
    - THIRDPARTY.yml
  summary: A blazingly fast library for computational linguistics
  documentation: https://docs.rustling.io/

extra:
  recipe-maintainers:
    - jacksonllee
